### ISSUE TITLE
GDB有池化资源能使用吗？

### ISSUE THREAD

**Issue by 0xCAFEBABE0** [aliyun/alibabacloud-gdb-java-sdk#1]
现在连接调用，每次都是通过cluster.connect()发起，connect方法的每次调用都新建Client对象，调用耗时上涨明显，是否有现成pool能进行池化资源管理呢？

**Comment by heljoyLiu** [comment]
client是线程安全的，内部有维护连接池，一般可以在应用启动时创建一次，期间可以多次sumbit，不需要每次交互都connect，在应用退出或不再使用时关掉client就行了
