### ISSUE TITLE
好像缺少httpcore包的引用

### ISSUE THREAD

**Issue by xiaoleizi2016** [aliyun/alibabacloud-gdb-java-sdk#2]
![image](https://user-images.githubusercontent.com/20458175/119071206-f5768280-ba1b-11eb-9ec2-5aebcad8b4ea.png)

**Comment by sandszhouSZ** [comment]
报什么错误？

**Comment by xiaoleizi2016** [comment]
![image](https://user-images.githubusercontent.com/20458175/119107841-32f60280-ba52-11eb-964f-3b7de3b2d853.png)

**Comment by sandszhouSZ** [comment]
![image](https://user-images.githubusercontent.com/41145333/119139248-5d0cec00-ba75-11eb-903d-dc2573839032.png)

这里的链路是完整的
