### ISSUE TITLE
Fork of the TinkerPop gremlin-driver

### ISSUE THREAD

**Issue by FlorianHockmann** [aliyun/alibabacloud-gdb-java-sdk#4]
Good to see that you have created a driver to access an Apache TinkerPop enabled database and thanks for sharing it with the community.

It looks to me like you mostly forked the TinkerPop gremlin-driver and then made modifications to it to implement your functionality. This is of course OK in general, but it would be good if you could state more clearly that your driver is based on the Apache TinkerPop driver. In order to do this, [the Apache v2 license explicitly requires](https://www.apache.org/licenses/LICENSE-2.0#redistribution) that the [NOTICE](https://github.com/apache/tinkerpop/blob/master/NOTICE) also needs to be included in a forked repository.
(You can leave out the parts of it that don't apply to code that you have used which are probably the lines 7-25.)

Thanks!

**Comment by sandszhouSZ** [comment]
Thanks your remainder, I will fix as soon as possible

**Comment by sandszhouSZ** [comment]
I added NOTICE file
